apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: poc
resources:
- ../../base



#namePrefix: dev-
#commonLabels:
#Â  env: dev

patches:
  - path: deployment.yaml
#  - path: ingress.yaml
